### ISSUE TITLE
Support Watch requests

### ISSUE THREAD

**Issue by chazsconi** [obmarg/kazan#12]
@obmarg In my project I need to support watch requests.

To do this I have written some code that can be used in the client as follows:
1. You create a request in the normal way, but setting `watch=true` e.g.
```
request = Kazan.Apis.CoreV1.list_namespace!(watch: "true")
```
2. You start a watcher using the request, and passing the initial resource version and a pid to which to send received messages.
```
Kazan.Watcher.start_link(request, resource_version: rv, send_to: self())
```
3. In your client code you receive messages for each `%Versioned.Event{}`.  You can pattern match on the object type if you have multiple watchers configured.  For example, if the client is a `GenServer`
```
  # type is "ADDED", "DELETED" or "MODIFIED"
  def handle_info(%Kazan.Models.Versioned.Event{object: object, type: type}, state) do
    case object do
      %Kazan.Models.V1.Namespace{} = namespace ->
        process_namespace_event(type, namespace)

      %Kazan.Models.V1.Job{} = job ->
        process_job_event(type, job)
    end
    {:noreply, state}
  end
```

Internally the `Watcher` does the following:
1. Initiates the request to `HTTPoison` using an AsyncRequest
2. Buffers chunks received from `HTTPoison` until a complete line of JSON is received.
3. Decodes the JSON and then decodes the K8S objects using `Kazan.Models.decode/1`
4. Sends the event to the client
5. Keeps track of the latest `resource_version` object received from K8S
6. Triggers another request, passing the latest `resource_version` when a `HTTPoison` timeout is received.

What do you think of this approach?  If you think this is the right way to do it, I will tidy up the code and submit a PR.

**Comment by obmarg** [comment]
Hey @chazsconi - thanks for filing this, and sorry about the delay responding.  I think that sounds like a good approach to the problem, I'd love to accept a PR that adds this as a feature.
