### ISSUE TITLE
Add auth config documentation

### ISSUE THREAD

**Issue by mayppong** [obmarg/kazan#17]
I'm trying to figure out how to configure the package, especially in the area of authenticating through ServiceAccount. I saw some the code in `Kazan.Server` on reading the kubecfg file. However, I'm not really sure where it's used, and the documentation isn't saying much about how to setup the auth component.

I'll keep looking around the repo but it would be really nice to have more info/example in the documentation or README.

I'm also happy to submit PR if you'd preferred.

**Comment by obmarg** [comment]
Hey @mayppong - thanks for checking out kazan.

Apologies if the documentation is unclear on this - I've tried to do a good job of pulling in docs from k8s, but I guess authentication is one of the things I'd have to document myself, and I've not done as good a job there.

I'll try to improve things in the future, but if you want to submit a PR after you've got things figured out that'd also be great.

In the meantime, here's a brief run down:  

So, you send requests to a k8s server using the [`Client.run`](https://hexdocs.pm/kazan/Kazan.Client.html#run/2) function.  This accepts an option `server` that should be a [`Kazan.Server`](https://hexdocs.pm/kazan/Kazan.Server.html#summary) struct that defines the server we want to talk to, and lets us know how to authenticate with it.

If you look in the documentation for [`Kazan.Server`](https://hexdocs.pm/kazan/Kazan.Server.html#summary) you'll see that there's 2 functions for constructing a `Kazan.Server` - `from_kubeconfig` and `in_cluster`.

- `in_cluster` is the function you want to call if your code is running inside kubernetes and you want to authenticate with the service account.
- `from_kubeconfig` takes the path to a kube config file and loads authentication details from there.

So you probably want to look into using one of those functions.

There's also some support for loading server parameters from your mix configuration, like so:

        config :kazan, :server, %{url: "kubernetes.default"}

but it's probably easiest to use the `Kazan.Server.in_cluster` function for now.  I'd totally accept a PR that makes the mix config loading support this use case a bit better though.  Maybe an `in_cluster` config option...?

Hope that all helps.

**Comment by mayppong** [comment]
Hey obmarg,

Thanks for the response. I got pull into another project last week but I'm getting back into this now. I `in_cluster` authentication is very much what I'm looking for. I must have missed that while looking through the documentation and source code.

Once I have a working code, I'll se if I can make it into an example for the README file. I think more example of Usage would be helpful.

Thank you,

**Comment by obmarg** [comment]
Hey @mayppong - I've ended up adding some documentation around authentication in acaf78c.  Would you mind letting me know what you think?

**Comment by mayppong** [comment]
Yes this is much more helpful. Thank you so much.

**Comment by obmarg** [comment]
Thanks @mayppong - I'm going to close this issue, but feel free to re-open if you think there's more improvements to be made.
