### ISSUE TITLE
Default file name for ca_cert in `Kazan.Server.in_cluster`

### ISSUE THREAD

**Issue by mayppong** [obmarg/kazan#25]
I notice the `in_cluster` function is looking for `ca.key` file name.

I believe this have changed according to Kubernetes' documentation on [accessing the API server from a pod](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod)
```
If available, a certificate bundle is placed into the filesystem tree of each container at
/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,
and should be used to verify the serving certificate of the apiserver.
```

I am running into this error while testing.
```
** (File.Error) could not read file "/var/run/secrets/kubernetes.io/serviceaccount/ca.key": no such file or directory
    (elixir) lib/file.ex:272: File.read!/1
    (kazan) lib/kazan/server.ex:130: Kazan.Server.cert_from_pem/2
    (kazan) lib/kazan/server.ex:70: Kazan.Server.in_cluster/1
    (ephemeral) lib/ephemeral/kube.ex:154: Ephemeral.Kube.deploy/2
```

The documentation is from version 1.9 and I'm running 1.8 so at the very least these 2 versions are not using `ca.key` name anymore.

If my hypothesis is right, please let me know. I am happy to make a PR as well.

Thank you,

**Comment by obmarg** [comment]
Yeah, looks like you're right - I've checked the docs for 1.6 onwards, and they all say `ca.crt` rather than `ca.key`.  I wasn't able to find docs on this for 1.5, but even if this was correct behavior for 1.5, I think I'd rather support newer k8s versions.

I'd definitely accept a PR if you want to make one.

**Comment by mayppong** [comment]
I'm just about to start working on testing it out so I will make a PR as soon as I get it to work.

https://github.com/mayppong/kazan/tree/ca-cert-filename

**Comment by mayppong** [comment]
So while working on this I ran into an issue with domain name not found.
```
iex(ephemeral@127.0.0.1)1> Ephemeral.Kube.deploy("test-kube-module", "aggiq")
** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :nxdomain}}
    (ephemeral) lib/ephemeral/kube.ex:154: Ephemeral.Kube.deploy/2
```

Looking back at Kubernetes' [doc](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod), they recommend to either run a `kubectl proxy` or use their Go library client. Either case seems idea to my use-case. However a quick look through their `InClusterConfig` [source code](https://github.com/kubernetes/client-go/blob/9f7db9794b9bd0183e59f73486b930e3733ff4c0/rest/config.go#L310) I looks like they're using environment variables that are set in each pod ,`KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`.

```
host, port := os.Getenv("KUBERNETES_SERVICE_HOST"), os.Getenv("KUBERNETES_SERVICE_PORT")
```
Do you think `kazan` should change the url of the cluster to those environment as well for its `in_cluster`? I'm happy to slap that in as part of the PR.

Thank you,

**Comment by obmarg** [comment]
@mayppong if those env variables are there then yeah, we should probably use them to override the default DNS name.

As an aside: you've made me realize I probably need a better way of testing our in cluster auth as part of a release...

**Comment by mayppong** [comment]
Yeah, I'm not super sure how I'm going to unit test things like these env var because unless I run the test in k8s, I won't get those variables. I'd hate to hardcode it. I'm testing in both my minikube as well as in our staging cluster so hopefully that covers enough ground.

That said I'm going to be looking into connection timeout issue when trying to do `Kazan.run`.

**Comment by obmarg** [comment]
@mayppong Don't worry too much about unit tests for this - I have some plans to put together an integration test, but its way too involved for me ask someone else to do it :)

**Comment by mayppong** [comment]
Hey, @obmarg I need a little bit of help if you don't mind.

I'm able to curl to the API server no problem using the environment variables mentioned above.
```
/app # curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" \
       https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT
{
  "paths": [
    "/api",
    "/api/v1",
    ...
  ]
}
```

However, when I try it in Elixir, I'm getting an error.
```
iex(ephemeral@127.0.0.1)1> HTTPoison.request("get", "https://10.96.0.1:443", "", [Authorization: "Bearer #{token}"], [timeout: :infinity, recv_timeout: :infinity])
{:error,
 %HTTPoison.Error{id: nil,
  reason: {:options, {{:server_name_indication, '10.96.0.1'}}}}}
  
iex(ephemeral@127.0.0.1)2> :hackney.request("get", "https://10.96.0.1:443", [Authorization: "Bearer #{token}"], "", [timeout: :infinity, recv_timeout: :infinity])
{:error, {:options, {{:server_name_indication, '10.96.0.1'}}}}
```

I could get `hackney` to work request at Google's home page just fine though.
```
:hackney.request("get", "https://google.com")
```

I'm not sure what's going on. I know this isn't directly related to `kazan` but I'd appreciate the help if you can. I think you might understand the context of what I'm trying to do better than trying to post this over at HTTPoison's page.

Thank you,

**Comment by obmarg** [comment]
@mayppong what version of erlang & hackney are you using?

**Comment by mayppong** [comment]
```
Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]
Interactive Elixir (1.5.2)
{:hex, :hackney, "1.6.5" ...
```

**Comment by obmarg** [comment]
@mayppong what minor version of otp 20 is that?  Running this should tell you:

    erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell

**Comment by obmarg** [comment]
Assuming you've not already got it, you might need to pull in at least erlang/otp 20.2.  

I _believe_ versions prior to that didn't accept IP addresses for doing SSL SNI.  [Looks like that was changed in this commit](https://github.com/erlang/otp/commit/78a9a09af9216a2dea454f561e0774e67a15c361).  Just a guess, but looks pretty consistent with your error...

**Comment by mayppong** [comment]
It looks like I'm running 20.1.2 version of Erlang. Well, I'm actually running docker image `elixir:1.5-alpine` which apparently is using that.

I will try upgrading to the new Elixir 1.6 image and see which version of Erlang it's running. It would be nice to not have to manually update Erlang. In any case, I hope this works, but will report back regardless.

**Comment by obmarg** [comment]
@mayppong was pretty late when I was messaging you last night, but I've now had time to test this myself.  I'm usually running erlang 20.2 and it worked fine, but I just reverted to 20.1 and sure enough:

```
iex(1)> HTTPoison.get("https://192.168.99.100:8443")
{:error,
 %HTTPoison.Error{
   id: nil,
   reason: {:options, {{:server_name_indication, '192.168.99.100'}}}
 }}
```

**Comment by obmarg** [comment]
I created a gitter room recently for kazan, you're welcome to join if you'd like a bit more interactive help: https://gitter.im/kazan-k8s/Lobby
