### ISSUE TITLE
If the response is not JSON then it should not be decoded

### ISSUE THREAD

**Issue by chazsconi** [obmarg/kazan#29]
Some requests, e.g: `Core.read_namespaced_pod_log/3` return a response type of `text/plain` and not `application/json`

In this case the response should not be JSON decoded and should just be returned as the raw response.

I'll create a PR to fix this by checking the response type before JSON and Model decoding.

**Comment by obmarg** [comment]
Nice find @chazsconi - will definitely accept a PR around this.

**Comment by obmarg** [comment]
From looking in the OAI spec, it seems like `Core.read_namespaced_pod_log` is the only request that can return `text/plain`.

It also lists JSON, YAML & protobuf under it's `produces` key though (although it's unclear how to get it to return in those formats) so guess we can't special case it.

I guess we'll just need to check the content-type of the request before decoding.
