### ISSUE TITLE
Format code with Elixir 1.6 formatter

### ISSUE THREAD

**Issue by chazsconi** [obmarg/kazan#32]
I suggest that to improve consistency, the code is formatted with the Elixir 1.6 formatter, a `.formatter.exs` is committed, and the Travis configuration is changed to run `mix format --check-formatted` in addition to the default `mix test`.

Happy to create a PR for this.

**Comment by obmarg** [comment]
Yep, this has been on my TODO list for a while - I've only been holding off to avoid merge conflicts with #14.

Would rather do this myself if that's OK - I've got some strong feels about formatting.  Happy to do it now if you're not bothered about any merge-related fall out in #14.

**Comment by chazsconi** [comment]
I'll send you the PR for #14 very soon - I almost have it ready, so it would be better to do the formatting after.

**Comment by obmarg** [comment]
Cool - no rush.  I'll get the code formatted after you're done.
