### ISSUE TITLE
Watcher process leaks if using old version of HTTPoison

### ISSUE THREAD

**Issue by chazsconi** [obmarg/kazan#73]
Due to https://github.com/edgurgel/httpoison/issues/375 (which I created a PR to fix, and is now merged) if you use HTTPoison < v1.6.1 you will have a process leak when using watches whenever a GONE event is received from K8S.

Therefore should Kazan's deps be changed to force using this version or later of HTTPoison, or should this just be warned about in the docs?

I'm happy to create a PR for either option.

**Comment by obmarg** [comment]
Ah nice - I saw similar problems in a project I had based on HTTPoison a few years ago.  Good to see someone fixing it.

I think it'd be fine to require > HTTPoison >= 1.6.1 - I'm assuming there's no breaking API changes, and people can always use an `override: true` dep if they _really_ need an older verson.

**Comment by chazsconi** [comment]
OK - done. https://github.com/obmarg/kazan/pull/74
